### ISSUE TITLE
Stylint crashes when parsing files with variables that don't start with `$`

### ISSUE THREAD

**Issue by hdavidzhu** [AtomLinter/linter-stylint#85] opened 2017-08-09 23:30 UTC
```
[{"filePath":"<REDACTED>","messages":[{"severity":"Error","message":"variables and parameters must be prefixed with the $ sign","rule":"prefixVarsWithDollar","line":3,"column":0},{"severity":"Error","message":"variables and parameters must be prefixed with the $ sign","rule":"prefixVarsWithDollar","line":4,"column":0}...
```

**Comment by hdavidzhu** [comment] 2017-08-10 00:01
Actually, I don't think this was the real error. I suspect this has to do with it:

https://github.com/AtomLinter/linter-stylint/issues/74

**Comment by Arcanemagus** [comment] 2017-08-18 15:49
I'm betting you are correct here, so I'll mark this as a duplicate for now.

**Comment by Arcanemagus** [comment] 2017-08-18 15:49
Duplicate of #74

**Closed by Arcanemagus** 2017-08-18 15:49 UTC
